title: <p align="center"> Mohammad Shahenshah </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/shahen-shah/">LinkedIn</a> |
  <a href="https://github.com/shahez">GitHub</a>
  
  <br>   
  Hello, I'm Shahenshah ğŸš€ Passionate Software Engineer | 
  ğŸŒ Open Source Enthusiast | ğŸ“š Lifelong Learner
  Let's code together and make the world a better place.
  <br>
  I have total of 8 Years of experience in multiple domains
  with technical expertise on Javascript, AWS, Java and Python.
  <br>
  </p>



theme: jekyll-theme-minimal